name: build-push

on:
  push:
    branches:
      - 'MAIN'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mfaishal882/clean-api-img:latest
      - 
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              docker stop api-alta-dashboard
              docker rm api-alta-dashboard
              docker rmi mfaishal882/api-alta-dashboard-img
              docker run --name api-alta-dashboard --link mysqlContainer -d -p 8000:8000 -e SERVER_PORT=${{secrets.SERVER_PORT}} -e DB_USERNAME=${{secrets.DB_USERNAME}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} -e DB_HOST=${{secrets.DB_HOST}}  -e DB_PORT=${{secrets.DB_PORT}}  -e DB_NAME=${{secrets.DB_NAME}} -e JWT_SECRET=${{secrets.JWT_SECRET}} mfaishal882/api-alta-dashboard-img




          
 
